Repository kyma-project/rafter, pull requests merged in 2019-11, with the labels that each got.

#16 Add support for Buckets in AssetGroup
  cmd/manager/main.go
  config/crd/bases/rafter.kyma-project.io_assetgroups.yaml
  config/crd/bases/rafter.kyma-project.io_clusterassetgroups.yaml
  config/crd/kustomization.yaml
  go.mod
  go.sum
  internal/controllers/assetgroup_controller_test.go
  internal/controllers/clusterassetgroup_controller_test.go
  internal/handler/assetgroup/assetgroup.go
  internal/handler/assetgroup/assetgroup_test.go
  pkg/apis/rafter/v1beta1/assetgroup_common.go
Labels: area/core-and-supporting

#15 Create build pipelines for Rafter
  .dockerignore
  Makefile
  cmd/extension/asyncapi/README.md
  cmd/extension/asyncapi/main.go
  cmd/extension/frontmatter/README.md
  cmd/extension/frontmatter/main.go
  cmd/manager/README.md
  cmd/manager/main.go
  cmd/uploader/README.md
  cmd/uploader/main.go
  config/crd/bases/rafter.kyma-project.io_assetgroups.yaml
  config/crd/bases/rafter.kyma-project.io_assets.yaml
  config/crd/bases/rafter.kyma-project.io_buckets.yaml
  config/crd/bases/rafter.kyma-project.io_clusterassetgroups.yaml
  config/crd/bases/rafter.kyma-project.io_clusterassets.yaml
  config/crd/bases/rafter.kyma-project.io_clusterbuckets.yaml
  config/crd/kustomization.yaml
  config/manager/kustomization.yaml
  deploy/extension/asyncapi/Dockerfile
  deploy/extension/frontmatter/Dockerfile
  deploy/manager/Dockerfile
  deploy/uploader/Dockerfile
  go.sum
  internal/handler/assetgroup/assetgroup_test.go
  pkg/apis/rafter/v1beta1/zz_generated.deepcopy.go
Labels: area/ci, area/core-and-supporting, enhancement

#20 Integration tests pipeline
  .gitignore
  Makefile
  hack/ci/config/kind/cluster-config.yaml
  hack/ci/config/kind/ingress.yaml
  hack/ci/envs.sh
  hack/ci/run-integration-tests.sh
  hack/ci/start_docker.sh
  hack/ci/test-helper.sh
  tests/asset-store/Makefile
  tests/asset-store/main_test.go
Labels: area/ci, area/core-and-supporting, enhancement

#24 Add JUnit reports for integration test
  go.mod
  go.sum
  hack/ci/run-integration-tests.sh
  hack/ci/test-helper.sh
  tests/asset-store/.gitignore
  tests/asset-store/Dockerfile
  tests/asset-store/before-commit.sh
Labels: area/core-and-supporting, enhancement

#31 Fix source label in docker containers
  deploy/extension/asyncapi/Dockerfile
  deploy/extension/frontmatter/Dockerfile
  deploy/manager/Dockerfile
  deploy/uploader/Dockerfile
Labels: area/core-and-supporting, enhancement

#25 JUnit for unit tests
  Makefile
  go.sum
  hack/ci/test-helper.sh
  hack/ci/unit_tests.sh
Labels: area/core-and-supporting, enhancement
