Repository kyma-project/rafter, pull requests merged in 2019-12, with the labels that each got.

#27 MinIO Gateway integration pipelines
  Makefile
  charts/rafter-upload-service/README.md
  charts/rafter-upload-service/templates/_helpers.tpl
  charts/rafter-upload-service/templates/migrator-job.yaml
  charts/rafter-upload-service/values.yaml
  charts/rafter/README.md
  charts/rafter/requirements.lock
  charts/rafter/values.yaml
  go.mod
  hack/ci/envs.sh
  hack/ci/lib/minio/azure-gateway.sh
  hack/ci/lib/minio/gateway-basic.sh
  hack/ci/lib/minio/gateway-helpers.sh
  hack/ci/lib/minio/gateway-migration.sh
  hack/ci/lib/minio/gcs-gateway.sh
  hack/ci/lib/test-helpers.sh
  hack/ci/run-integration-test.sh
  hack/ci/run-integration-tests.sh
  hack/ci/run-minio-gateway-test.sh
  hack/ci/run-unit-tests.sh
  hack/ci/start-docker.sh
  hack/ci/start_docker.sh
  hack/ci/test-helper.sh
  hack/ci/unit_tests.sh
Labels: area/core-and-supporting, enhancement

#32 Update samples
  config/samples/rafter_v1beta1_assetgroup.yaml
  config/samples/rafter_v1beta1_clusterassetgroup.yaml
Labels: area/core-and-supporting, enhancement

#35 Update casing in values.yaml in charts and fix gateway jobs on master
  charts/rafter-upload-service/templates/migrator-job.yaml
  charts/rafter-upload-service/values.yaml
  charts/rafter/values.yaml
  hack/ci/lib/minio/azure-gateway.sh
  hack/ci/run-minio-gateway-test.sh
Labels: area/core-and-supporting, enhancement

#34 Add a development guide
  README.md
  cmd/extension/asyncapi/README.md
  cmd/extension/frontmatter/README.md
  cmd/manager/README.md
  cmd/uploader/README.md
  docs/development-guide.md
  tests/asset-store/README.md
Labels: area/documentation

#38 Adjust metrics and dashboard
  go.mod
  internal/requesthandler/requesthandler.go
  internal/route/extract.go
  internal/uploader/uploader.go
  pkg/extractor/extractor.go
  pkg/processor/processor.go
  pkg/runtime/endpoint/mutation_endpoint.go
  pkg/runtime/endpoint/validation_endpoint.go
Labels: WIP, area/core-and-supporting, area/monitoring

#17 Apply changes from PR #6058 from Kyma to Rafter to stabilize integration tests
  Makefile
  config/crd/bases/rafter.kyma-project.io_assetgroups.yaml
  config/crd/bases/rafter.kyma-project.io_assets.yaml
  config/crd/bases/rafter.kyma-project.io_buckets.yaml
  config/crd/bases/rafter.kyma-project.io_clusterassetgroups.yaml
  config/crd/bases/rafter.kyma-project.io_clusterassets.yaml
  config/crd/bases/rafter.kyma-project.io_clusterbuckets.yaml
  deploy/extension/asyncapi/Dockerfile
  deploy/extension/frontmatter/Dockerfile
  deploy/manager/Dockerfile
  deploy/uploader/Dockerfile
  go.mod
  go.sum
  pkg/apis/rafter/v1beta1/zz_generated.deepcopy.go
  tests/asset-store/pkg/namespace/namespace.go
  tests/asset-store/pkg/resource/resource.go
  tests/asset-store/pkg/retry/retry.go
  tests/asset-store/pkg/retry/retry_test.go
  tests/asset-store/testsuite/asset.go
  tests/asset-store/testsuite/bucket.go
  tests/asset-store/testsuite/clusterasset.go
  tests/asset-store/testsuite/clusterbucket.go
  tests/asset-store/testsuite/common.go
  tests/asset-store/testsuite/testdata.go
  tests/asset-store/testsuite/testsuite.go
Labels: area/core-and-supporting, enhancement

#40 Add Rafter Katacoda tutorials
  docs/README.md
  docs/katacoda-tutorials/README.md
  docs/katacoda-tutorials/basic/finish.md
  docs/katacoda-tutorials/basic/index.json
  docs/katacoda-tutorials/basic/intro.md
  docs/katacoda-tutorials/basic/setup.sh
  docs/katacoda-tutorials/basic/step1.md
  docs/katacoda-tutorials/basic/step2.md
  docs/katacoda-tutorials/basic/step3.md
  docs/katacoda-tutorials/basic/step4.md
Labels: area/documentation

#43 Move the tutorials to the root
  docs/README.md
  katacoda-tutorials/README.md
  katacoda-tutorials/finish.md
  katacoda-tutorials/index.json
  katacoda-tutorials/intro.md
  katacoda-tutorials/setup.sh
  katacoda-tutorials/step1.md
  katacoda-tutorials/step2.md
  katacoda-tutorials/step3.md
  katacoda-tutorials/step4.md
Labels: area/documentation

#44 Fix a broken link
  katacoda-tutorials/README.md
  katacoda-tutorials/setup.sh
Labels: area/documentation

#45 Add installation instructions
  README.md
Labels: area/core-and-supporting, enhancement

#46 Update Rafter links
  README.md
  cmd/extension/frontmatter/README.md
  cmd/uploader/README.md
  katacoda-tutorials/step2.md
Labels: area/documentation
