Repository kyma-project/rafter, pull requests merged in 2020-01, with the labels that each got.

#49 Add configMap mode to loader structure
  charts/rafter-controller-manager/templates/assetgroups.crd.yaml
  charts/rafter-controller-manager/templates/assets.crd.yaml
  charts/rafter-controller-manager/templates/buckets.crd.yaml
  charts/rafter-controller-manager/templates/clusterassetgroups.crd.yaml
  charts/rafter-controller-manager/templates/clusterassets.crd.yaml
  charts/rafter-controller-manager/templates/clusterbuckets.crd.yaml
  cmd/manager/main.go
  config/crd/bases/rafter.kyma-project.io_assets.yaml
  config/crd/bases/rafter.kyma-project.io_clusterassets.yaml
  go.mod
  go.sum
  internal/loader/configmap_loader.go
  internal/loader/configmap_loader_test.go
  internal/loader/loader.go
  pkg/apis/rafter/v1beta1/asset_common_types.go
  tests/pkg/configmap/configmap.go
  tests/testdata/bar.png
  tests/testdata/foo.json
  tests/testsuite/testsuite.go
Labels: area/core-and-supporting, enhancement

#63 Enable stale bot for epics
  .github/stale.yml
Labels: area/community

#62 Add a tutorial showing the use of ConfigMaps in Rafter
  README.md
  katacoda-tutorials/index.json
  katacoda-tutorials/step2.md
  katacoda-tutorials/step3.md
  katacoda-tutorials/step4.md
  katacoda-tutorials/step5.md
Labels: area/documentation

#64 Remove additional indents from tutorials
  CODEOWNERS
  katacoda-tutorials/step3.md
  katacoda-tutorials/step5.md
Labels: area/documentation
